Latvian translation
rms-support-letter/rms-support-letter.github.io pull request #2764
Opened 2021-03-26 11:48 UTC by doctorx32

2021-03-26 17:22 UTC, doctorx32 commented
ready to review

2021-03-26 17:56 UTC, shenlebantongying commented
We changed the format a bit, can you check the main repo and rearrange `:)`

2021-03-26 18:33 UTC, doctorx32 commented
removed that line with flag

2021-03-26 22:50 UTC, nukeop commented
Can you please add the little changes that were recently merged into other translations (flag etc)?

2021-03-26 22:52 UTC, kristapsk requested changes

2021-03-26 22:52 UTC, kristapsk commented on README_LV.md
> +Lai parakstītu, **uzspiediet [šeit](https://github.com/rms-support-letter/rms-support-letter.github.io/new/master/_data/signed)** un uzsauciet failu `<username>.yaml` (nomainiet `<username>` ar Jūsu
```suggestion
Lai parakstītu, **spiediet [šeit](https://github.com/rms-support-letter/rms-support-letter.github.io/new/master/_data/signed)** un nosauciet failu `<username>.yaml` (nomainiet `<username>` ar Jūsu vārdu) ar sekojošu saturu:
```

2021-03-26 22:52 UTC, kristapsk commented on README_LV.md
> +link: <link uz Jūsu profilu vai vietni>
```suggestion
link: <saite uz Jūsu profilu vai vietni>
```

2021-03-26 22:52 UTC, kristapsk commented on README_LV.md
> +Lūdzu nelietojiet `<>` šajā failā, tapat kā non-ascii simbolus faila nosaukuma.
```suggestion
Lūdzu nelietojiet `<>` šajā failā, tapat kā non-ascii simbolus faila nosaukumā.
```

2021-03-26 22:52 UTC, kristapsk commented on README_LV.md
> +Jas Jūs lietosiet e-pastu kā linku, izveidojiet prefiksu ar `mailto:`.
```suggestion
Ja Jūs lietosiet e-pastu kā saiti, izmantojiet `mailto:` prefiksu.
```

2021-03-26 22:52 UTC, kristapsk commented on index_lv.md
> +Richard M. Stallman, bieži pazīstams kā RMS,
```suggestion
Ričards Stalmans (Richard M. Stallman), bieži pazīstams arī kā RMS,
```

2021-03-26 22:52 UTC, kristapsk commented on index_lv.md
> +kustību gadu desmitiem, ieskaitot ieguldījumus
```suggestion
ir bijis brīvās programmatūras kustību virzītājspēks
gadu desmitiem, ieskaitot ieguldījumus
```

2021-03-26 22:52 UTC, kristapsk commented on index_lv.md
> +GNU operētājsistēma un Emacs.
```suggestion
GNU operētājsistēmā un teksta redaktorā Emacs.
```

2021-03-26 22:52 UTC, kristapsk commented on index_lv.md
> +šīs kopienas ikona tiek uzbrūkta.
Nesen ir notikuši nežēlīgi tiešsaistes uzbrukumi ar mērķi
noņemt viņu nost no Brīvās Programmatūras Fonda (Free Software Foundation, tālāk tekstā - FSF) direktoru padomes
par personīgā viedokļa paušanu. Mēs esam jau agrāk
redzējuši, kā tas notiek ar citiem brīvās programmatūras aktīvistiem
un programmētājiem organizētā veidā. Šoreiz, kad tiek uzbrukts šīs
kopienas ikonai, mēs nestāvēsim malā.

2021-03-26 22:52 UTC, kristapsk commented on index_lv.md
> +un patiesi saprast viņa vārdu nozīmi un darbības.
FSF ir neatkarīga iestāde, kas spēj attiekties pret
tās locekļiem taisnīgā un objektīvā veidā un
neļausies ārējam sociālam spiedienam. Mēs aicinām
FSF objektīvi izskatīt argumentus pret RMS
un patiesi saprast viņa vārdu nozīmi un darbības.

2021-03-26 22:52 UTC, kristapsk commented on index_lv.md
> +ņemot vērā, ka biežāk viņš nemeklē lietas diplomātiski.
RMS vēsturiski ir paudis savu viedokli veidos, kas ir satraucis
daudzus cilvēkus. Viņš parasti vairāk uzmanību vērš uz filozofisko
pamatojumu, kā arī seko objektīvai patiesībai un valodas pūrismam,
vienlaikus nepietiekami domājot par cilvēku jūtām jautājumos, ko viņš
komentē. Tas padara viņa argumentus neaizsargātākus pret pārpratumiem
un sagrozījumiem, kas, mūsuprāt, ir noticis arī šajā gadījumā ar atvērto
vēstuli ar aicinājumu viņu atcelt no amata. Viņa vārdi ir jāvērtē šajā kontekstā
un arī jāņem vērā, ka parasti viņš nepieiet lietām diplomātiski.

2021-03-26 22:52 UTC, kristapsk commented on index_lv.md
> +Turklāt viņam ir tiesības uz savu viedokli, kā jebkuram citām.
```suggestion
Neatkarīgi no tā, Stalmana viedoklis par šiem jautājumiem
neietekmē viņa spēju vadīt tādu sabiedrību kā FSF.
Turklāt viņam ir tiesības uz savu viedokli, kā jebkuram citam. 
```

2021-03-26 22:52 UTC, kristapsk commented on index_lv.md
> +Biedri un atbalstītājiem var nepiekrīt viņa uzskatiem,
```suggestion
Biedriem un atbalstītājiem ir tiesības nepiekrist viņa uzskatiem, 
```

2021-03-26 22:52 UTC, kristapsk commented on index_lv.md
> +par programmatūras nozares nākotni.
```suggestion
programmatūras nozares nākotni.
```

2021-03-26 22:52 UTC, kristapsk commented on index_lv.md
> +pauž desmitiem gadus kā sabiedrisks darbinieks: **
```suggestion
** Ļaunprāšu pūlim, kuri uzbrūk Ričardam Stalmanam par gadu desmitiem paustiem saprātīgiem argumentiem un citādākiem viedokļiem, ko tas paudis kā sabiedrisks darbinieks: **
```

2021-03-26 22:52 UTC, kristapsk commented on index_lv.md
> +cilvēki, piemēram kā Ričards Stallmans.
Jums nav nekādu tiesību izvēlēties jebkādu kopienu vadību. Īpaši ar
kolektīvu iebiedēšanu, kas pat attālināti nav salīdzināma ar godīgu
diskusiju, ar ko nodarbojas labāki cilvēki par jums, piemēram, Ričards
Stalmans.

2021-03-26 22:52 UTC, kristapsk commented on index_lv.md
> +Lai paraksīt, lūdzu [sūtiet Pull
```suggestion
Lai parakstītu, lūdzu [sūtiet Pull
```

2021-03-26 22:52 UTC, kristapsk commented on index_lv.md
> +description: Atvērta vēstule atbalstam Richard Matthew Stallman the Free Software Foundation atjaunošanai
```suggestion
title: Atklāta vēstule Ričarda Stalmana atbalstam
description: Atklāta vēstule paužot atbalstu Ričarda Metjū Stalmana atjaunošanai Brīvās Programmatūras Fonda direktoru padomes satāvā
```

2021-03-27 13:02 UTC, doctorx32 commented
@kristapsk paldies!

@nukeop I have done it by moving index_lv.md to /_translations, is it correct?

2021-03-27 14:48 UTC, imachug commented
Thanks, looks great!

2021-03-27 14:48 UTC, merged